[workspace]
resolver = "2"

members = [
    "src/dedust_api_client",
    "src/stonfi_api_client",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/Sild/api_clients_rs"

[workspace.dependencies]
tokio = { version = "1.41", features = ["full"] }
tokio-macros = "2.4"
anyhow = "1.0"
log = "0.4"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
log4rs = "1.0"
serde_yaml = "0.9"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
json = "0.12.4"
tokio-test = "0.4.4"
moka = "0.12.8"
strum = "0.26.3"
strum_macros = "0.26.3"
serde_with = "3.11.0"
serde_qs = "0.13.0"
serde_derive = "1.0.214"
env_logger = "0.11"
reqwest-retry = "0.6"
reqwest-middleware = "0.3"
